
workflows:
  ios-release:
    name: iOS Release

    environment:
      flutter: stable
      xcode: latest


    scripts:

      - name: Flutter packages
        script: |
          flutter pub get

      - name: Build iOS dependencies only
        script: |
          cd ios
          flutter build ios --config-only --no-codesign

      - name: Patch Pods project
        script: |
          cd ios

        sed -i '' "s/platform , '13.0'/platform , '15.0'/g" Podfile || true
        sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g" Runner.xcodeproj/project.pbxproj || true

        cd ..

        flutter build ios --config-only --no-codesign
          echo "Pods patched."

      - name: Final iOS build
        script: |
          flutter build ios --release --no-codesign
