// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-firebase-web-api-key',
    appId: '1:000000000000:web:c2da596450b3ae3ef8705e',
    messagingSenderId: '000000000000',
    projectId: 'dummy-firebase-project-id',
    authDomain: 'dummy-firebase-project-id.firebaseapp.com',
    databaseURL: 'https://dummy-firebase-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-firebase-project-id.firebasestorage.app',
    measurementId: 'G-DUMMYWEB1234',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy-firebase-android-api-key',
    appId: '1:000000000000:android:e55177d128c003b9f8705e',
    messagingSenderId: '000000000000',
    projectId: 'dummy-firebase-project-id',
    databaseURL: 'https://dummy-firebase-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-firebase-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-firebase-ios-api-key',
    appId: '1:000000000000:ios:6ad5cc255ed5a422f8705e',
    messagingSenderId: '000000000000',
    projectId: 'dummy-firebase-project-id',
    databaseURL: 'https://dummy-firebase-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-firebase-project-id.firebasestorage.app',
    iosBundleId: 'com.lubeindicator.myapp',
  );

}